<?php

namespace WeProvide\ConfigBundle\Repository;

/**
 * ConfigVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
