<?php

namespace WeProvide\ConfigBundle\Repository;

/**
 * ConfigValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigValueRepository extends \Doctrine\ORM\EntityRepository
{
}
