<?php

namespace WeProvide\ConfigBundle\Repository;

/**
 * ConfigVariableChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigVariableChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
